/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e567c45c-ddb5-4a5f-9a88-9860925230f6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Z37ahGGMw",
    "aws_user_pools_web_client_id": "68svtrlf4b0q63dutnbtodlsb2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zrleg6qbtjfm7cl7bvqsvcqlba.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
